package org.domain.seammysql.entity;

// Generated Mar 8, 2013 4:46:14 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * BaseDate generated by hbm2java
 */
@Entity
@Table(name = "BASE_DATE", catalog = "takion77_db")
public class BaseDate implements java.io.Serializable {

	private String bssd;
	private String prevBssd;
	private String nextBssd;
	private String eomBssd;

	public BaseDate() {
	}

	public BaseDate(String bssd) {
		this.bssd = bssd;
	}

	public BaseDate(String bssd, String prevBssd, String nextBssd,
			String eomBssd) {
		this.bssd = bssd;
		this.prevBssd = prevBssd;
		this.nextBssd = nextBssd;
		this.eomBssd = eomBssd;
	}

	@Id
	@Column(name = "BSSD", unique = true, nullable = false, length = 8)
	@NotNull
	@Size(max = 8)
	public String getBssd() {
		return this.bssd;
	}

	public void setBssd(String bssd) {
		this.bssd = bssd;
	}

	@Column(name = "PREV_BSSD", length = 8)
	@Size(max = 8)
	public String getPrevBssd() {
		return this.prevBssd;
	}

	public void setPrevBssd(String prevBssd) {
		this.prevBssd = prevBssd;
	}

	@Column(name = "NEXT_BSSD", length = 8)
	@Size(max = 8)
	public String getNextBssd() {
		return this.nextBssd;
	}

	public void setNextBssd(String nextBssd) {
		this.nextBssd = nextBssd;
	}

	@Column(name = "EOM_BSSD", length = 8)
	@Size(max = 8)
	public String getEomBssd() {
		return this.eomBssd;
	}

	public void setEomBssd(String eomBssd) {
		this.eomBssd = eomBssd;
	}

}
