SET SESSION FOREIGN_KEY_CHECKS=0;

/* Drop Tables */

DROP TABLE PORTFOLIO_LOSS;
DROP TABLE PORTFOLIO_HIS;
DROP TABLE PORTFOLIO_DETAIL;
DROP TABLE POSITION_LOSS;
DROP TABLE POSITION_HIS;
DROP TABLE BASE_DATE;
DROP TABLE POSITION;
DROP TABLE DEALER;
DROP TABLE LGD_SEG;
DROP TABLE PD_SEG;
DROP TABLE PORTFOLIO;
DROP TABLE PRODUCT;




/* Create Tables */

CREATE TABLE BASE_DATE
(
	BSSD VARCHAR(8) NOT NULL COMMENT '기준일자 ',
	PREV_BSSD VARCHAR(8) COMMENT '직전 기준일자(영업일자)',
	NEXT_BSSD VARCHAR(8) COMMENT '다음 기준일자(영업일자)',
	EOM_BSSD VARCHAR(8) COMMENT '해당일의 월말 기준일자(영업일자)',
	PRIMARY KEY (BSSD)
);


CREATE TABLE DEALER
(
	ID VARCHAR(50) NOT NULL,
	NAME VARCHAR(50),
	DEPARTMET_ID VARCHAR(10),
	PRIMARY KEY (ID)
);


CREATE TABLE LGD_SEG
(
	ID VARCHAR(20) NOT NULL,
	NAME VARCHAR(50),
	GROUP_ID VARCHAR(20),
	RATE_CD VARCHAR(20),
	COLLATERAL_CD VARCHAR(20),
	LGD DECIMAL(10,8),
	PRIMARY KEY (ID)
);


CREATE TABLE PD_SEG
(
	ID VARCHAR(20) NOT NULL,
	NAME VARCHAR(50),
	GROUP_ID VARCHAR(20),
	RATE_CD VARCHAR(20),
	IND_CD VARCHAR(20),
	PD DECIMAL(10,8),
	PRIMARY KEY (ID)
);


CREATE TABLE PORTFOLIO
(
	ID VARCHAR(50) NOT NULL,
	NAME VARCHAR(50),
	PARENT_PORT_ID VARCHAR(50),
	LEVEL1 VARCHAR(20),
	LEVEL2 VARCHAR(20),
	LEVEL3 VARCHAR(20),
	LEVEL4 VARCHAR(20),
	LEVEL5 VARCHAR(20),
	PRIMARY KEY (ID)
);


CREATE TABLE PORTFOLIO_DETAIL
(
	BSSD VARCHAR(8) NOT NULL COMMENT '기준일자 ',
	PORTFOLIO_ID VARCHAR(50) NOT NULL,
	POSITION_ID VARCHAR(50) NOT NULL,
	PRIMARY KEY (BSSD, PORTFOLIO_ID, POSITION_ID)
);


CREATE TABLE PORTFOLIO_HIS
(
	BSSD VARCHAR(8) NOT NULL COMMENT '기준일자 ',
	PORTFOLIO_ID VARCHAR(50) NOT NULL,
	PORT_AMT DECIMAL(20,2),
	PRIMARY KEY (BSSD, PORTFOLIO_ID)
);


CREATE TABLE PORTFOLIO_LOSS
(
	BSSD VARCHAR(8) NOT NULL COMMENT '기준일자 ',
	PORTFOLIO_ID VARCHAR(50) NOT NULL,
	LOSS_ID VARCHAR(20) NOT NULL,
	LOSS_AMT DECIMAL(20,2),
	LOSS_PROB DECIMAL(10,8),
	PRIMARY KEY (BSSD, PORTFOLIO_ID, LOSS_ID)
);


CREATE TABLE POSITION
(
	ID VARCHAR(50) NOT NULL,
	NAME VARCHAR(50),
	PRODUCT_ID VARCHAR(50) NOT NULL,
	DEALER_ID VARCHAR(50) NOT NULL,
	POS_AMT DECIMAL(20,2),
	PRIMARY KEY (ID)
);


CREATE TABLE POSITION_HIS
(
	BSSD VARCHAR(8) NOT NULL COMMENT '기준일자 ',
	POSITION_ID VARCHAR(50) NOT NULL,
	HOLD_QTY DECIMAL(19,4),
	POS_AMT DECIMAL(20,2),
	PRIMARY KEY (BSSD, POSITION_ID)
);


CREATE TABLE POSITION_LOSS
(
	BSSD VARCHAR(8) NOT NULL COMMENT '기준일자 ',
	POSITION_ID VARCHAR(50) NOT NULL,
	LOSS_NO VARCHAR(20) NOT NULL,
	LOSS_AMT DECIMAL(20,2),
	LOST_PROB DECIMAL(10,8),
	PRIMARY KEY (BSSD, POSITION_ID, LOSS_NO)
);


CREATE TABLE PRODUCT
(
	ID VARCHAR(50) NOT NULL,
	NAME VARCHAR(50),
	TYPE VARCHAR(10),
	PRIMARY KEY (ID)
);



/* Create Foreign Keys */

ALTER TABLE PORTFOLIO_HIS
	ADD FOREIGN KEY (BSSD)
	REFERENCES BASE_DATE (BSSD)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE POSITION_HIS
	ADD FOREIGN KEY (BSSD)
	REFERENCES BASE_DATE (BSSD)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE POSITION
	ADD FOREIGN KEY (DEALER_ID)
	REFERENCES DEALER (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE PORTFOLIO
	ADD FOREIGN KEY (PARENT_PORT_ID)
	REFERENCES PORTFOLIO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE PORTFOLIO_DETAIL
	ADD FOREIGN KEY (PORTFOLIO_ID)
	REFERENCES PORTFOLIO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE PORTFOLIO_HIS
	ADD FOREIGN KEY (PORTFOLIO_ID)
	REFERENCES PORTFOLIO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE PORTFOLIO_LOSS
	ADD FOREIGN KEY (BSSD, PORTFOLIO_ID)
	REFERENCES PORTFOLIO_HIS (BSSD, PORTFOLIO_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE POSITION_HIS
	ADD FOREIGN KEY (POSITION_ID)
	REFERENCES POSITION (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE PORTFOLIO_DETAIL
	ADD FOREIGN KEY (BSSD, POSITION_ID)
	REFERENCES POSITION_HIS (BSSD, POSITION_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE POSITION_LOSS
	ADD FOREIGN KEY (BSSD, POSITION_ID)
	REFERENCES POSITION_HIS (BSSD, POSITION_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE POSITION
	ADD FOREIGN KEY (PRODUCT_ID)
	REFERENCES PRODUCT (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



