
/* Drop Tables */

DROP TABLE TAKION77.PORTFOLIO_LOSS;
DROP TABLE TAKION77.PORTFOLIO_HIS;
DROP TABLE TAKION77.PORTFOLIO_DETAIL;
DROP TABLE TAKION77.POSITION_LOSS;
DROP TABLE TAKION77.POSITION_HIS;
DROP TABLE TAKION77.BASE_DATE;
DROP TABLE TAKION77.POSITION;
DROP TABLE TAKION77.DEALER;
DROP TABLE TAKION77.LGD_SEG;
DROP TABLE TAKION77.PD_SEG;
DROP TABLE TAKION77.PORTFOLIO;
DROP TABLE TAKION77.PRODUCT;




/* Create Tables */

CREATE TABLE TAKION77.BASE_DATE
(
	BSSD VARCHAR2(8) NOT NULL,
	PREV_BSSD VARCHAR2(8),
	NEXT_BSSD VARCHAR2(8),
	EOM_BSSD VARCHAR2(8),
	PRIMARY KEY (BSSD)
);


CREATE TABLE TAKION77.DEALER
(
	ID VARCHAR2(50) NOT NULL,
	NAME VARCHAR2(50),
	DEPARTMET_ID VARCHAR2(10),
	PRIMARY KEY (ID)
);


CREATE TABLE TAKION77.LGD_SEG
(
	ID VARCHAR2(20) NOT NULL,
	NAME VARCHAR2(50),
	GROUP_ID VARCHAR2(20),
	RATE_CD VARCHAR2(20),
	COLLATERAL_CD VARCHAR2(20),
	LGD NUMBER(10,8),
	PRIMARY KEY (ID)
);


CREATE TABLE TAKION77.PD_SEG
(
	ID VARCHAR2(20) NOT NULL,
	NAME VARCHAR2(50),
	GROUP_ID VARCHAR2(20),
	RATE_CD VARCHAR2(20),
	IND_CD VARCHAR2(20),
	PD NUMBER(10,8),
	PRIMARY KEY (ID)
);


CREATE TABLE TAKION77.PORTFOLIO
(
	ID VARCHAR2(50) NOT NULL,
	NAME VARCHAR2(50),
	PARENT_PORT_ID VARCHAR2(50),
	LEVEL1 VARCHAR2(20),
	LEVEL2 VARCHAR2(20),
	LEVEL3 VARCHAR2(20),
	LEVEL4 VARCHAR2(20),
	LEVEL5 VARCHAR2(20),
	PRIMARY KEY (ID)
);


CREATE TABLE TAKION77.PORTFOLIO_DETAIL
(
	BSSD VARCHAR2(8) NOT NULL,
	PORTFOLIO_ID VARCHAR2(50) NOT NULL,
	POSITION_ID VARCHAR2(50) NOT NULL,
	PRIMARY KEY (BSSD, PORTFOLIO_ID, POSITION_ID)
);


CREATE TABLE TAKION77.PORTFOLIO_HIS
(
	BSSD VARCHAR2(8) NOT NULL,
	PORTFOLIO_ID VARCHAR2(50) NOT NULL,
	PORT_AMT NUMBER(20,2),
	PRIMARY KEY (BSSD, PORTFOLIO_ID)
);


CREATE TABLE TAKION77.PORTFOLIO_LOSS
(
	BSSD VARCHAR2(8) NOT NULL,
	PORTFOLIO_ID VARCHAR2(50) NOT NULL,
	LOSS_ID VARCHAR2(20) NOT NULL,
	LOSS_AMT NUMBER(20,2),
	LOSS_PROB NUMBER(10,8),
	PRIMARY KEY (BSSD, PORTFOLIO_ID, LOSS_ID)
);


CREATE TABLE TAKION77.POSITION
(
	ID VARCHAR2(50) NOT NULL,
	NAME VARCHAR2(50),
	PRODUCT_ID VARCHAR2(50) NOT NULL,
	DEALER_ID VARCHAR2(50) NOT NULL,
	POS_AMT NUMBER(20,2),
	PRIMARY KEY (ID)
);


CREATE TABLE TAKION77.POSITION_HIS
(
	BSSD VARCHAR2(8) NOT NULL,
	POSITION_ID VARCHAR2(50) NOT NULL,
	HOLD_QTY NUMBER(19,4),
	POS_AMT NUMBER(20,2),
	PRIMARY KEY (BSSD, POSITION_ID)
);


CREATE TABLE TAKION77.POSITION_LOSS
(
	BSSD VARCHAR2(8) NOT NULL,
	POSITION_ID VARCHAR2(50) NOT NULL,
	LOSS_NO VARCHAR2(20) NOT NULL,
	LOSS_AMT NUMBER(20,2),
	LOST_PROB NUMBER(10,8),
	PRIMARY KEY (BSSD, POSITION_ID, LOSS_NO)
);


CREATE TABLE TAKION77.PRODUCT
(
	ID VARCHAR2(50) NOT NULL,
	NAME VARCHAR2(50),
	TYPE VARCHAR2(10),
	PRIMARY KEY (ID)
);



/* Create Foreign Keys */

ALTER TABLE TAKION77.PORTFOLIO_HIS
	ADD FOREIGN KEY (BSSD)
	REFERENCES BASE_DATE (BSSD)
;


ALTER TABLE TAKION77.POSITION_HIS
	ADD FOREIGN KEY (BSSD)
	REFERENCES BASE_DATE (BSSD)
;


ALTER TABLE TAKION77.POSITION
	ADD FOREIGN KEY (DEALER_ID)
	REFERENCES DEALER (ID)
;


ALTER TABLE TAKION77.PORTFOLIO
	ADD FOREIGN KEY (PARENT_PORT_ID)
	REFERENCES PORTFOLIO (ID)
;


ALTER TABLE TAKION77.PORTFOLIO_DETAIL
	ADD FOREIGN KEY (PORTFOLIO_ID)
	REFERENCES PORTFOLIO (ID)
;


ALTER TABLE TAKION77.PORTFOLIO_HIS
	ADD FOREIGN KEY (PORTFOLIO_ID)
	REFERENCES PORTFOLIO (ID)
;


ALTER TABLE TAKION77.PORTFOLIO_LOSS
	ADD FOREIGN KEY (BSSD, PORTFOLIO_ID)
	REFERENCES PORTFOLIO_HIS (BSSD, PORTFOLIO_ID)
;


ALTER TABLE TAKION77.POSITION_HIS
	ADD FOREIGN KEY (POSITION_ID)
	REFERENCES POSITION (ID)
;


ALTER TABLE TAKION77.PORTFOLIO_DETAIL
	ADD FOREIGN KEY (BSSD, POSITION_ID)
	REFERENCES POSITION_HIS (BSSD, POSITION_ID)
;


ALTER TABLE TAKION77.POSITION_LOSS
	ADD FOREIGN KEY (BSSD, POSITION_ID)
	REFERENCES POSITION_HIS (BSSD, POSITION_ID)
;


ALTER TABLE TAKION77.POSITION
	ADD FOREIGN KEY (PRODUCT_ID)
	REFERENCES PRODUCT (ID)
;



/* Comments */

COMMENT ON COLUMN BASE_DATE.BSSD IS '기준일자 ';
COMMENT ON COLUMN BASE_DATE.PREV_BSSD IS '직전 기준일자(영업일자)';
COMMENT ON COLUMN BASE_DATE.NEXT_BSSD IS '다음 기준일자(영업일자)';
COMMENT ON COLUMN BASE_DATE.EOM_BSSD IS '해당일의 월말 기준일자(영업일자)';
COMMENT ON COLUMN PORTFOLIO_DETAIL.BSSD IS '기준일자 ';
COMMENT ON COLUMN PORTFOLIO_HIS.BSSD IS '기준일자 ';
COMMENT ON COLUMN PORTFOLIO_LOSS.BSSD IS '기준일자 ';
COMMENT ON COLUMN POSITION_HIS.BSSD IS '기준일자 ';
COMMENT ON COLUMN POSITION_LOSS.BSSD IS '기준일자 ';



