
/* Drop Tables */

DROP TABLE PORTFOLIO_DETAIL;
DROP TABLE PORTFOLIO;
DROP TABLE POSITION_DETAIL;
DROP TABLE POSITION;




/* Create Tables */

CREATE TABLE PORTFOLIO
(
	ID VARCHAR2(50) NOT NULL,
	NAME VARCHAR2(50),
	PARENT_PORT_ID VARCHAR2(50) NOT NULL,
	PRIMARY KEY (ID)
);


CREATE TABLE PORTFOLIO_DETAIL
(
	-- 기준일자 
	BSSD VARCHAR2(8) NOT NULL,
	PORTFOLIO_ID VARCHAR2(50) NOT NULL,
	POSITION_ID VARCHAR2(50) NOT NULL,
	PRIMARY KEY (BSSD, PORTFOLIO_ID, POSITION_ID)
);


CREATE TABLE POSITION
(
	ID VARCHAR2(50) NOT NULL,
	NAME VARCHAR2(50),
	PRODUCT_ID VARCHAR2(50) NOT NULL,
	DEALER_ID VARCHAR2(50) NOT NULL,
	PRIMARY KEY (ID)
);


CREATE TABLE POSITION_DETAIL
(
	-- 기준일자 
	BSSD VARCHAR2(8) NOT NULL,
	POSITION_ID VARCHAR2(50) NOT NULL,
	HOLD_QTY NUMBER(19,4),
	PRIMARY KEY (BSSD, POSITION_ID)
);



/* Create Foreign Keys */

ALTER TABLE PORTFOLIO
	ADD FOREIGN KEY (PARENT_PORT_ID)
	REFERENCES PORTFOLIO (ID)
;


ALTER TABLE PORTFOLIO_DETAIL
	ADD FOREIGN KEY (PORTFOLIO_ID)
	REFERENCES PORTFOLIO (ID)
;


ALTER TABLE POSITION_DETAIL
	ADD FOREIGN KEY (POSITION_ID)
	REFERENCES POSITION (ID)
;


ALTER TABLE PORTFOLIO_DETAIL
	ADD FOREIGN KEY (BSSD, POSITION_ID)
	REFERENCES POSITION_DETAIL (BSSD, POSITION_ID)
;



/* Comments */

COMMENT ON COLUMN PORTFOLIO_DETAIL.BSSD IS '기준일자 ';
COMMENT ON COLUMN POSITION_DETAIL.BSSD IS '기준일자 ';



