package org.domain.revtest.entity;

// Generated Mar 8, 2013 4:58:15 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * PortfolioDetailId generated by hbm2java
 */
@Embeddable
public class PortfolioDetailId implements java.io.Serializable {

	private String bssd;
	private String portfolioId;
	private String positionId;

	public PortfolioDetailId() {
	}

	public PortfolioDetailId(String bssd, String portfolioId, String positionId) {
		this.bssd = bssd;
		this.portfolioId = portfolioId;
		this.positionId = positionId;
	}

	@Column(name = "BSSD", nullable = false, length = 8)
	@NotNull
	@Size(max = 8)
	public String getBssd() {
		return this.bssd;
	}

	public void setBssd(String bssd) {
		this.bssd = bssd;
	}

	@Column(name = "PORTFOLIO_ID", nullable = false, length = 50)
	@NotNull
	@Size(max = 50)
	public String getPortfolioId() {
		return this.portfolioId;
	}

	public void setPortfolioId(String portfolioId) {
		this.portfolioId = portfolioId;
	}

	@Column(name = "POSITION_ID", nullable = false, length = 50)
	@NotNull
	@Size(max = 50)
	public String getPositionId() {
		return this.positionId;
	}

	public void setPositionId(String positionId) {
		this.positionId = positionId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PortfolioDetailId))
			return false;
		PortfolioDetailId castOther = (PortfolioDetailId) other;

		return ((this.getBssd() == castOther.getBssd()) || (this.getBssd() != null
				&& castOther.getBssd() != null && this.getBssd().equals(
				castOther.getBssd())))
				&& ((this.getPortfolioId() == castOther.getPortfolioId()) || (this
						.getPortfolioId() != null
						&& castOther.getPortfolioId() != null && this
						.getPortfolioId().equals(castOther.getPortfolioId())))
				&& ((this.getPositionId() == castOther.getPositionId()) || (this
						.getPositionId() != null
						&& castOther.getPositionId() != null && this
						.getPositionId().equals(castOther.getPositionId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getBssd() == null ? 0 : this.getBssd().hashCode());
		result = 37
				* result
				+ (getPortfolioId() == null ? 0 : this.getPortfolioId()
						.hashCode());
		result = 37
				* result
				+ (getPositionId() == null ? 0 : this.getPositionId()
						.hashCode());
		return result;
	}

}
