package org.domain.revtest.entity;

// Generated Mar 8, 2013 4:58:15 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

/**
 * PositionDetail generated by hbm2java
 */
@Entity
@Table(name = "POSITION_DETAIL", catalog = "takion77_db")
public class PositionDetail implements java.io.Serializable {

	private PositionDetailId id;
	private BigDecimal holdQty;

	public PositionDetail() {
	}

	public PositionDetail(PositionDetailId id) {
		this.id = id;
	}

	public PositionDetail(PositionDetailId id, BigDecimal holdQty) {
		this.id = id;
		this.holdQty = holdQty;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "bssd", column = @Column(name = "BSSD", nullable = false, length = 8)),
			@AttributeOverride(name = "positionId", column = @Column(name = "POSITION_ID", nullable = false, length = 50)) })
	@NotNull
	public PositionDetailId getId() {
		return this.id;
	}

	public void setId(PositionDetailId id) {
		this.id = id;
	}

	@Column(name = "HOLD_QTY", scale = 4)
	public BigDecimal getHoldQty() {
		return this.holdQty;
	}

	public void setHoldQty(BigDecimal holdQty) {
		this.holdQty = holdQty;
	}

}
