package com.eugene.element;

// Generated 2012. 12. 31 ¿ÀÈÄ 6:19:47 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * AccountMst generated by hbm2java
 */
@Entity
@Table(name = "ACCOUNT_MST")
public class AccountMst implements java.io.Serializable {

	private String id;
	private String name;
	private String parentId;
	private Set<Position> positions = new HashSet<Position>(0);

	public AccountMst() {
	}

	public AccountMst(String id) {
		this.id = id;
	}

	public AccountMst(String id, String name, String parentId, Set<Position> positions) {
		this.id = id;
		this.name = name;
		this.parentId = parentId;
		this.positions = positions;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 20)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "NAME", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "PARENT_ID", length = 20)
	public String getParentId() {
		return this.parentId;
	}

	public void setParentId(String parentId) {
		this.parentId = parentId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "accountMst")
	public Set<Position> getPositions() {
		return this.positions;
	}

	public void setPositions(Set<Position> positions) {
		this.positions = positions;
	}

}
