package com.eugene.element;

// Generated 2012. 12. 20 ¿ÀÈÄ 5:18:49 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Dealer generated by hbm2java
 */
@Entity
@Table(name = "DEALER")
public class Dealer implements java.io.Serializable {

	private String id;
	private String name;
	private String departId;

	public Dealer() {
	}

	public Dealer(String id) {
		this.id = id;
	}

	public Dealer(String id, String name, String departId) {
		this.id = id;
		this.name = name;
		this.departId = departId;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 30)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "NAME", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "DEPART_ID", length = 30)
	public String getDepartId() {
		return this.departId;
	}

	public void setDepartId(String departId) {
		this.departId = departId;
	}

}
