package com.eugene.element;

// Generated 2012. 12. 20 ¿ÀÈÄ 5:18:49 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Portfolio generated by hbm2java
 */
@Entity
@Table(name = "PORTFOLIO")
public class Portfolio implements java.io.Serializable {

	private String id;
	private String name;
	private String parentId;

	public Portfolio() {
	}

	public Portfolio(String id, String parentId) {
		this.id = id;
		this.parentId = parentId;
	}

	public Portfolio(String id, String name, String parentId) {
		this.id = id;
		this.name = name;
		this.parentId = parentId;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 30)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "NAME", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "PARENT_ID", nullable = false, length = 30)
	public String getParentId() {
		return this.parentId;
	}

	public void setParentId(String parentId) {
		this.parentId = parentId;
	}

}
