package com.eugene.element;

// Generated 2012. 12. 31 ¿ÀÈÄ 6:19:47 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PortfolioHis generated by hbm2java
 */
@Entity
@Table(name = "PORTFOLIO_HIS")
public class PortfolioHis implements java.io.Serializable {

	private PortfolioHisId id;
	private Portfolio portfolio;
	private BigDecimal portAmt;
	private Set<PortfolioLoss> portfolioLosses = new HashSet<PortfolioLoss>(0);

	public PortfolioHis() {
	}

	public PortfolioHis(PortfolioHisId id, Portfolio portfolio) {
		this.id = id;
		this.portfolio = portfolio;
	}

	public PortfolioHis(PortfolioHisId id, Portfolio portfolio, BigDecimal portAmt,
			Set<PortfolioLoss> portfolioLosses) {
		this.id = id;
		this.portfolio = portfolio;
		this.portAmt = portAmt;
		this.portfolioLosses = portfolioLosses;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "bssd", column = @Column(name = "BSSD", nullable = false, length = 8)),
			@AttributeOverride(name = "portfolioId", column = @Column(name = "PORTFOLIO_ID", nullable = false, length = 50)) })
	public PortfolioHisId getId() {
		return this.id;
	}

	public void setId(PortfolioHisId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PORTFOLIO_ID", nullable = false, insertable = false, updatable = false)
	public Portfolio getPortfolio() {
		return this.portfolio;
	}

	public void setPortfolio(Portfolio portfolio) {
		this.portfolio = portfolio;
	}

	@Column(name = "PORT_AMT", precision = 20)
	public BigDecimal getPortAmt() {
		return this.portAmt;
	}

	public void setPortAmt(BigDecimal portAmt) {
		this.portAmt = portAmt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "portfolioHis")
	public Set<PortfolioLoss> getPortfolioLosses() {
		return this.portfolioLosses;
	}

	public void setPortfolioLosses(Set<PortfolioLoss> portfolioLosses) {
		this.portfolioLosses = portfolioLosses;
	}

}
