package com.eugene.element;

// Generated 2012. 12. 31 ¿ÀÈÄ 6:19:47 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Position generated by hbm2java
 */
@Entity
@Table(name = "POSITION")
public class Position implements java.io.Serializable {

	private String id;
	private Obligor obligor;
	private Dealer dealer;
	private Product product;
	private AccountMst accountMst;
	private String name;
	private BigDecimal posAmt;
	private String colCd;
	private Set<PositionHis> positionHises = new HashSet<PositionHis>(0);

	public Position() {
	}

	public Position(String id) {
		this.id = id;
	}

	public Position(String id, Obligor obligor, Dealer dealer, Product product,
			AccountMst accountMst, String name, BigDecimal posAmt, String colCd,
			Set<PositionHis> positionHises) {
		this.id = id;
		this.obligor = obligor;
		this.dealer = dealer;
		this.product = product;
		this.accountMst = accountMst;
		this.name = name;
		this.posAmt = posAmt;
		this.colCd = colCd;
		this.positionHises = positionHises;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 100)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "OBLIGOR_ID")
	public Obligor getObligor() {
		return this.obligor;
	}

	public void setObligor(Obligor obligor) {
		this.obligor = obligor;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DEALER_ID")
	public Dealer getDealer() {
		return this.dealer;
	}

	public void setDealer(Dealer dealer) {
		this.dealer = dealer;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRODUCT_ID")
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ACCOUNT_ID")
	public AccountMst getAccountMst() {
		return this.accountMst;
	}

	public void setAccountMst(AccountMst accountMst) {
		this.accountMst = accountMst;
	}

	@Column(name = "NAME", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "POS_AMT", precision = 20)
	public BigDecimal getPosAmt() {
		return this.posAmt;
	}

	public void setPosAmt(BigDecimal posAmt) {
		this.posAmt = posAmt;
	}

	@Column(name = "COL_CD", length = 20)
	public String getColCd() {
		return this.colCd;
	}

	public void setColCd(String colCd) {
		this.colCd = colCd;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "position")
	public Set<PositionHis> getPositionHises() {
		return this.positionHises;
	}

	public void setPositionHises(Set<PositionHis> positionHises) {
		this.positionHises = positionHises;
	}

}
