package com.eugene.element;

// Generated 2012. 12. 20 ¿ÀÈÄ 5:18:49 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * PositionDetail generated by hbm2java
 */
@Entity
@Table(name = "POSITION_DETAIL")
public class PositionDetail implements java.io.Serializable {

	private PositionDetailId id;
	private BigDecimal holingQty;
	private String prodId;

	public PositionDetail() {
	}

	public PositionDetail(PositionDetailId id, String prodId) {
		this.id = id;
		this.prodId = prodId;
	}

	public PositionDetail(PositionDetailId id, BigDecimal holingQty,
			String prodId) {
		this.id = id;
		this.holingQty = holingQty;
		this.prodId = prodId;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "bssd", column = @Column(name = "BSSD", nullable = false, length = 8)),
			@AttributeOverride(name = "id", column = @Column(name = "ID", nullable = false, length = 30)) })
	public PositionDetailId getId() {
		return this.id;
	}

	public void setId(PositionDetailId id) {
		this.id = id;
	}

	@Column(name = "HOLING_QTY", precision = 20, scale = 4)
	public BigDecimal getHolingQty() {
		return this.holingQty;
	}

	public void setHolingQty(BigDecimal holingQty) {
		this.holingQty = holingQty;
	}

	@Column(name = "PROD_ID", nullable = false, length = 30)
	public String getProdId() {
		return this.prodId;
	}

	public void setProdId(String prodId) {
		this.prodId = prodId;
	}

}
