package com.eugene.element;

// Generated 2012. 12. 31 ¿ÀÈÄ 2:16:29 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Position generated by hbm2java
 */
@Entity
@Table(name = "POSITION")
public class Position implements java.io.Serializable {

	private String id;
	private Dealer dealer;
	private Product product;
	private String name;
	private BigDecimal posAmt;
	private Set<PositionHis> positionHises = new HashSet<PositionHis>(0);

	public Position() {
	}

	public Position(String id, Dealer dealer, Product product) {
		this.id = id;
		this.dealer = dealer;
		this.product = product;
	}

	public Position(String id, Dealer dealer, Product product, String name, BigDecimal posAmt,
			Set<PositionHis> positionHises) {
		this.id = id;
		this.dealer = dealer;
		this.product = product;
		this.name = name;
		this.posAmt = posAmt;
		this.positionHises = positionHises;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 50)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DEALER_ID", nullable = false)
	public Dealer getDealer() {
		return this.dealer;
	}

	public void setDealer(Dealer dealer) {
		this.dealer = dealer;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRODUCT_ID", nullable = false)
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@Column(name = "NAME", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "POS_AMT", precision = 20)
	public BigDecimal getPosAmt() {
		return this.posAmt;
	}

	public void setPosAmt(BigDecimal posAmt) {
		this.posAmt = posAmt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "position")
	public Set<PositionHis> getPositionHises() {
		return this.positionHises;
	}

	public void setPositionHises(Set<PositionHis> positionHises) {
		this.positionHises = positionHises;
	}

}
