package com.eugene.element;

// Generated 2012. 12. 20 ¿ÀÈÄ 5:18:49 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Position generated by hbm2java
 */
@Entity
@Table(name = "POSITION")
public class Position implements java.io.Serializable {

	private String id;
	private String name;
	private Character isOpen;
	private String prodId;
	private String ownerId;

	public Position() {
	}

	public Position(String id, String prodId, String ownerId) {
		this.id = id;
		this.prodId = prodId;
		this.ownerId = ownerId;
	}

	public Position(String id, String name, Character isOpen, String prodId,
			String ownerId) {
		this.id = id;
		this.name = name;
		this.isOpen = isOpen;
		this.prodId = prodId;
		this.ownerId = ownerId;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 30)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "NAME", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "IS_OPEN", length = 1)
	public Character getIsOpen() {
		return this.isOpen;
	}

	public void setIsOpen(Character isOpen) {
		this.isOpen = isOpen;
	}

	@Column(name = "PROD_ID", nullable = false, length = 30)
	public String getProdId() {
		return this.prodId;
	}

	public void setProdId(String prodId) {
		this.prodId = prodId;
	}

	@Column(name = "OWNER_ID", nullable = false, length = 30)
	public String getOwnerId() {
		return this.ownerId;
	}

	public void setOwnerId(String ownerId) {
		this.ownerId = ownerId;
	}

}
