package com.eugene.element;

// Generated 2012. 12. 31 ¿ÀÈÄ 6:19:47 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PositionLoss generated by hbm2java
 */
@Entity
@Table(name = "POSITION_LOSS")
public class PositionLoss implements java.io.Serializable {

	private PositionLossId id;
	private PositionHis positionHis;
	private BigDecimal lossAmt;
	private BigDecimal lossProb;

	public PositionLoss() {
	}

	public PositionLoss(PositionLossId id, PositionHis positionHis) {
		this.id = id;
		this.positionHis = positionHis;
	}
	public PositionLoss(PositionLossId id, BigDecimal lossAmt,BigDecimal lossProb) {
		this.id = id;
		this.lossAmt = lossAmt;
		this.lossProb = lossProb;
	}
	public PositionLoss(PositionLossId id, PositionHis positionHis, BigDecimal lossAmt,
			BigDecimal lossProb) {
		this.id = id;
		this.positionHis = positionHis;
		this.lossAmt = lossAmt;
		this.lossProb = lossProb;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "bssd", column = @Column(name = "BSSD", nullable = false, length = 8)),
			@AttributeOverride(name = "positionId", column = @Column(name = "POSITION_ID", nullable = false, length = 100)),
			@AttributeOverride(name = "lossNo", column = @Column(name = "LOSS_NO", nullable = false, length = 20)) })
	public PositionLossId getId() {
		return this.id;
	}

	public void setId(PositionLossId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "BSSD", referencedColumnName = "BSSD", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "POSITION_ID", referencedColumnName = "POSITION_ID", nullable = false, insertable = false, updatable = false) })
	public PositionHis getPositionHis() {
		return this.positionHis;
	}

	public void setPositionHis(PositionHis positionHis) {
		this.positionHis = positionHis;
	}

	@Column(name = "LOSS_AMT", precision = 20)
	public BigDecimal getLossAmt() {
		return this.lossAmt;
	}

	public void setLossAmt(BigDecimal lossAmt) {
		this.lossAmt = lossAmt;
	}

	@Column(name = "LOSS_PROB", precision = 10, scale = 8)
	public BigDecimal getLossProb() {
		return this.lossProb;
	}

	public void setLossProb(BigDecimal lossProb) {
		this.lossProb = lossProb;
	}

}
