package com.eugene.element;

// Generated 2012. 12. 31 ¿ÀÈÄ 2:16:29 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "PRODUCT")
public class Product implements java.io.Serializable {

	private String id;
	private String name;
	private String type;
	private Set<Position> positions = new HashSet<Position>(0);

	public Product() {
	}

	public Product(String id) {
		this.id = id;
	}

	public Product(String id, String name, String type, Set<Position> positions) {
		this.id = id;
		this.name = name;
		this.type = type;
		this.positions = positions;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 50)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "NAME", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "TYPE", length = 10)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	public Set<Position> getPositions() {
		return this.positions;
	}

	public void setPositions(Set<Position> positions) {
		this.positions = positions;
	}

}
